version: '3.8'

services:
  web:
    build: .
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adbdlogin
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: 9PiHioJ6CbVoFVGM
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
